const Terms = () => {
  return (
    <div className="bg-background">
      <div className="min-h-screen w-full  text-white flex flex-col border-y border-gray-600/30  h-full md:px-8 sm:px-6 px-2 pt-12 max-w-7xl mx-auto gap-6 text-justify">
        <h1 className="text-xl font-semibold mb-4">
          Terms and Conditions of Use
        </h1>
        <div>
          <h2 className="font-semibold">1. Introduction</h2>
          <p>
            Welcome to Caption Wizard (the "Website"), owned and operated by
            Maria Kaufmann ("we", "us", or "our"). These terms and conditions
            ("Terms") govern your access to and use of the Website. By accessing
            or using the Website, you agree to be bound by these Terms.
          </p>
        </div>
        <div>
          <h2 className="font-semibold">2. Definitions</h2>
          <p>
            "Website" refers to Caption Wizard, accessible via the URL
            https://captionwizard.onrender.com. "User" refers to any individual
            accessing or using the Website. "Credits" refer to virtual credits
            purchased by users for accessing premium features. "Content" refers
            to any videos, text, or other materials uploaded to or generated by
            the Website.
          </p>
        </div>
        <div>
          <h2 className="font-semibold">3. Account Registration</h2>
          <p>
            Users may be required to create an account to access certain
            features of the Website. Users agree to provide accurate and
            complete information when creating an account. Users are responsible
            for maintaining the security of their account credentials and for
            any activities conducted under their account.
          </p>
        </div>
        <div>
          <h2 className="font-semibold">4. Credits and Purchases</h2>
          <p>
            Users may purchase Credits to access premium features of the
            Website. All purchases are final and non-refundable, except as
            required by law. We reserve the right to modify the pricing of
            Credits at any time without prior notice.
          </p>
        </div>
        <div>
          <h2 className="font-semibold">5. User Content</h2>
          <p>
            Users retain ownership of any Content they upload to the Website. By
            uploading Content, users grant us a non-exclusive, royalty-free
            license to use, reproduce, and distribute the Content for the
            purpose of providing the services of the Website. Users are solely
            responsible for the Content they upload and must ensure it does not
            infringe on any third-party rights or violate any laws.
          </p>
        </div>
        <div>
          <h2 className="font-semibold">6. Intellectual Property</h2>
          <p>
            The Website and its contents, including but not limited to text,
            graphics, logos, and software, are the property of Maria Kaufmann
            and are protected by intellectual property laws. Users may not
            reproduce, distribute, or modify any part of the Website without our
            prior written consent.
          </p>
        </div>
        <div>
          <h2 className="font-semibold">7. Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by law, we disclaim any liability
            for any damages or losses arising out of or in connection with the
            use of the Website. We are not responsible for any Content uploaded
            by users or for any third-party websites linked to from the Website.
          </p>
        </div>
        <div>
          <h2 className="font-semibold">8. Governing Law</h2>
          <p>
            These Terms are governed by the laws of Israel. Any disputes arising
            out of or in connection with these Terms shall be resolved
            exclusively by the courts of Israel.
          </p>
        </div>
        <div>
          <h2 className="font-semibold">9. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. Changes will
            be effective immediately upon posting on the Website. Users are
            responsible for regularly reviewing these Terms.
          </p>
        </div>
        <div>
          <h2 className="font-semibold">10. Contact Information</h2>
          <p>
            For questions or concerns about these Terms, please contact us at{" "}
            <b>captionswizard@gmail.com.</b>
            <br />
            By accessing or using the Website, you acknowledge that you have
            read, understood, and agree to be bound by these Terms and our
            Privacy Policy.
          </p>
        </div>
        <p>Last updated: 05/08/2024</p>
      </div>
    </div>
  );
};

export default Terms;
