export const languageOptions = [
  { value: "bg", label: ["български", "Bulgarian"] },
  { value: "ca", label: ["Català", "Catalan"] },
  { value: "cs", label: ["Čeština", "Czech"] },
  { value: "da", label: ["Dansk", "Danish"] },
  { value: "nl", label: ["Nederlands", "Dutch"] },
  { value: "en", label: ["English", "English"] },
  { value: "et", label: ["Eesti keel", "Estonian"] },
  { value: "fi", label: ["Suomalainen", "Finnish"] },
  { value: "fr", label: ["Français", "French"] },
  { value: "de", label: ["Deutsch", "German"] },
  { value: "de-CH", label: ["Deutsch", "German (Switzerland)"] },
  { value: "el", label: ["Ελληνικά", "Greek"] },
  { value: "hi", label: ["हिंदी", "Hindi"] },
  { value: "hu", label: ["Magyar", "Hungarian"] },
  { value: "id", label: ["Bahasa Indonesia", "Indonesian"] },
  { value: "it", label: ["Italiano", "Italian"] },
  { value: "ja", label: ["日本語", "Japanese"] },
  { value: "ko", label: ["한국인", "Korean"] },
  { value: "lv", label: ["Latviski", "Latvian"] },
  { value: "lt", label: ["Lietuviešu", "Lithuanian"] },
  { value: "ms", label: ["Bahasa Melayu", "Malay"] },
  { value: "no", label: ["Norsk", "Norwegian"] },
  { value: "pl", label: ["Polskie", "Polish"] },
  { value: "pt", label: ["Português", "Portuguese"] },
  { value: "ro", label: ["Romunščina", "Romanian"] },
  { value: "ru", label: ["Русский", "Russian"] },
  { value: "sk", label: ["Slovenčina", "Slovak"] },
  { value: "es", label: ["Español", "Spanish"] },
  { value: "sv", label: ["Svenska", "Swedish"] },
  { value: "th", label: ["แบบไทย", "Thai"] },
  { value: "tr", label: ["Türkçe", "Turkish"] },
  { value: "uk", label: ["Українська", "Ukrainian"] },
  { value: "vi", label: ["Tiếng Việt", "Vietnamese"] },
];

export const demoOptions = [
  { language: "bg", demo: "Демо" },
  { language: "ca", demo: "Demostració" },
  { language: "cs", demo: "Demo" },
  { language: "da", demo: "Demo" },
  { language: "nl", demo: "Demo" },
  { language: "en", demo: "Demo" },
  { language: "et", demo: "Demo" },
  { language: "fi", demo: "Demo" },
  { language: "fr", demo: "Démo" },
  { language: "de", demo: "Demo" },
  { language: "de-CH", demo: "Demo" },
  { language: "el", demo: "διαδήλωση" },
  { language: "hi", demo: "डेमो" },
  { language: "hu", demo: "Demó" },
  { language: "id", demo: "Demo" },
  { language: "it", demo: "Demo" },
  { language: "ja", demo: "デモ" },
  { language: "ko", demo: "데모" },
  { language: "lv", demo: "Demo" },
  { language: "lt", demo: "Demo" },
  { language: "ms", demo: "Demo" },
  { language: "no", demo: "Demo" },
  { language: "pl", demo: "Próbny" },
  { language: "pt", demo: "Demonstração" },
  { language: "ro", demo: "Demonstrație" },
  { language: "ru", demo: "Демо" },
  { language: "sk", demo: "Demo" },
  { language: "es", demo: "Demostración" },
  { language: "sv", demo: "Demo" },
  { language: "th", demo: "การสาธิต" },
  { language: "tr", demo: "Demo" },
  { language: "uk", demo: "Демо" },
  { language: "vi", demo: "Demo" },
];


export const greekWeightOptions = [{ value: "GFS Didot Regular", label: "Regular" }];
export const hindiWeightOptions = [
  { value: "Tiro Devanagari Hindi Regular", label: "Regular" },
];
export const japaneseWeightOptions = [
  { value: "Noto Sans JP Regular", label: "Regular" },
  { value: "Noto Sans JP Medium", label: "Medium" },
  { value: "Noto Sans JP SemiBold", label: "SemiBold" },
  { value: "Noto Sans JP Bold", label: "Bold" },
  { value: "Noto Sans JP ExtraBold", label: "ExtraBold" },
  { value: "Noto Sans JP Black", label: "Black" },
];
export const koreanWeightOptions = [
  { value: "Noto Sans KR Regular", label: "Regular" },
  { value: "Noto Sans KR Medium", label: "Medium" },
  { value: "Noto Sans KR SemiBold", label: "SemiBold" },
  { value: "Noto Sans KR Bold", label: "Bold" },
  { value: "Noto Sans KR ExtraBold", label: "ExtraBold" },
  { value: "Noto Sans KR Black", label: "Black" },
];
export const thaiWeightOptions = [
  { value: "Kanit Regular", label: "Regular" },
  { value: "Kanit Medium", label: "Medium" },
  { value: "Kanit SemiBold", label: "SemiBold" },
  { value: "Kanit Bold", label: "Bold" },
  { value: "Kanit ExtraBold", label: "ExtraBold" },
  { value: "Kanit Black", label: "Black" },
];
export const montserratWeightOptions = [
  { value: "Montserrat Regular", label: "Regular" },
  { value: "Montserrat Medium", label: "Medium" },
  { value: "Montserrat SemiBold", label: "SemiBold" },
  { value: "Montserrat Bold", label: "Bold" },
  { value: "Montserrat ExtraBold", label: "ExtraBold" },
  { value: "Montserrat Black", label: "Black" },
];